# Generated by Django 5.2.6 on 2025-10-06 15:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RecyCon', '0002_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(limit_choices_to={'role': 'collector'}, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests_received', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_requests', to='RecyCon.product')),
                ('requester', models.ForeignKey(help_text='User who created the pickup request (household or buyer).', limit_choices_to=models.Q(('role', 'household'), ('role', 'buyer'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['requester', 'created_at'], name='Pickup_pick_request_822259_idx'), models.Index(fields=['collector', 'status'], name='Pickup_pick_collect_74c31a_idx')],
                'unique_together': {('requester', 'collector', 'product')},
            },
        ),
    ]
