# Generated by Django 5.2.6 on 2025-10-06 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('clean', 'Clean'), ('dry', 'Dry'), ('sorted', 'Sorted'), ('recycled', 'Recycled'), ('no_foreign_materials', 'No foreign materials'), ('no_battery', 'No battery'), ('no_liquid', 'No liquid'), ('broken', 'Broken'), ('nonfunctional', 'Nonfunctional'), ('metal_only', 'Metal only')], help_text='Quality/handling tags for marketplace items.', max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('metal', 'Metal'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('ewaste', 'E-waste'), ('glass', 'Glass')], max_length=20)),
                ('grade', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='marketplace/products/')),
                ('seller', models.ForeignKey(blank=True, help_text='Seller must be an approved Collector/Buyer/Recycler.', limit_choices_to={'is_approved': True, 'role__in': ['collector', 'buyer', 'recycler']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='Marketplace.markettag')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=120)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_sales', to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Marketplace.marketplace')),
            ],
            options={
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['buyer', 'created_at'], name='Marketplace_buyer_i_63a166_idx'), models.Index(fields=['collector', 'status'], name='Marketplace_collect_7a1ed0_idx')],
            },
        ),
    ]
