# Generated by Django 5.2 on 2025-09-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='product_type',
            field=models.CharField(choices=[('metal', 'Metal'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('ewaste', 'E-waste')], default='metal', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='short_description1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='short_description2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
