# Generated by Django 5.2.6 on 2025-10-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_create_marketorder_if_missing'),
    ]

    operations =  []
