# Generated by Django 5.2.6 on 2025-10-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_marketplace_product_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marketplace',
        ),
    ]
