# Generated by Django 5.2.6 on 2025-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('clean', 'Clean'), ('dry', 'Dry'), ('sorted', 'Sorted'), ('no_foreign_materials', 'No foreign materials'), ('no_battery', 'No battery'), ('no_liquid', 'No liquid'), ('broken', 'Broken'), ('nonfunctional', 'Nonfunctional'), ('metal_only', 'Metal only')], db_index=True, help_text='Quality/handling tags for marketplace items.', max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('metal', 'Metal'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('ewaste', 'E-waste'), ('glass', 'Glass')], max_length=20)),
                ('grade', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='Marketplace.markettag')),
            ],
        ),
    ]
