# Generated by Django 5.2.6 on 2025-10-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0003_rename_marketplace_buyer_i_d92b9d_idx_marketplace_buyer_i_63a166_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketorder',
            new_name='Marketplace_buyer_i_63a166_idx',
            old_name='marketplace_buyer_i_d92b9d_idx',
        ),
        migrations.RenameIndex(
            model_name='marketorder',
            new_name='Marketplace_collect_7a1ed0_idx',
            old_name='marketplace_collect_a22bcc_idx',
        ),
        migrations.AlterModelTable(
            name='marketorder',
            table='Marketplace_marketorder',
        ),
        migrations.AlterModelTable(
            name='marketplace',
            table='Marketplace_marketplace',
        ),
        migrations.AlterModelTable(
            name='markettag',
            table='Marketplace_markettag',
        ),
    ]
