# Generated by Django 5.2.6 on 2025-10-11 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0004_rename_marketplace_buyer_i_d92b9d_idx_marketplace_buyer_i_63a166_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller must be an approved Buyer/Recycler.', limit_choices_to={'is_approved': True, 'role__in': ['buyer', 'recycler']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
