# Generated by Django 5.2.6 on 2025-10-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettag',
            name='name',
            field=models.CharField(choices=[('clean', 'Clean'), ('dry', 'Dry'), ('sorted', 'Sorted'), ('recycled', 'Recycled'), ('no_foreign_materials', 'No foreign materials'), ('no_battery', 'No battery'), ('no_liquid', 'No liquid'), ('broken', 'Broken'), ('nonfunctional', 'Nonfunctional'), ('metal_only', 'Metal only')], db_index=True, help_text='Quality/handling tags for marketplace items.', max_length=40, unique=True),
        ),
    ]
