# Generated by Django 5.2.6 on 2025-10-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='marketplace/products/'),
        ),
    ]
