# Generated by Django 5.2.6 on 2025-10-03 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='marketplace',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller must be an approved Collector/Buyer/Recycler.', limit_choices_to={'is_approved': True, 'role__in': ['collector', 'buyer', 'recycler']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='markettag',
            name='name',
            field=models.CharField(choices=[('clean', 'Clean'), ('dry', 'Dry'), ('sorted', 'Sorted'), ('recycled', 'Recycled'), ('no_foreign_materials', 'No foreign materials'), ('no_battery', 'No battery'), ('no_liquid', 'No liquid'), ('broken', 'Broken'), ('nonfunctional', 'Nonfunctional'), ('metal_only', 'Metal only')], help_text='Quality/handling tags for marketplace items.', max_length=40, unique=True),
        ),
    ]
