# Generated by Django 5.2.6 on 2025-10-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0004_initial'),
        ('Marketplace', '0005_alter_markettag_name'),
        ('Marketplace', '0006_marketplace_product_image'),
        ('Marketplace', '0007_alter_marketplace_options_marketplace_seller_and_more'),
    ]

    operations = [
    ]
