# Generated by Django 5.2.6 on 2025-09-22 12:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('e_waste', 'E-waste')], help_text='Product type', max_length=10)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in your currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ('kind',),
            },
        ),
    ]
