# Generated by Django 5.2.6 on 2025-09-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Learn',
            new_name='Guide',
        ),
    ]
