# Generated by Django 5.2 on 2025-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_rename_learn_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Sorting', 'Sorting'), ('Environment', 'Environment'), ('Recycling', 'Recycling')], max_length=50)),
                ('description', models.TextField()),
                ('read_time', models.PositiveIntegerField(help_text='Reading time in minutes')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='guides/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.AddField(
            model_name='learn',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Education.tag'),
        ),
    ]
