# Generated by Django 5.2.6 on 2025-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_learn_tag_delete_guide_learn_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learn',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='learn',
            name='quick_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learn',
            name='topic',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='learn',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='category',
            field=models.CharField(choices=[('guideline', 'Guideline'), ('article', 'Article'), ('video', 'Video'), ('quick_text', 'Quick Text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learn',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guides/covers/'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='guides', to='Education.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('environment', 'Environment'), ('recycle', 'Recycle'), ('pollution', 'Pollution'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('e_waste', 'E-waste'), ('metal', 'Metal'), ('glass', 'Glass'), ('carbon_footprint', 'Carbon Footprint'), ('green_jobs', 'Green Jobs'), ('landfill_reduction', 'Landfill Reduction')], db_index=True, help_text='Select a predefined tag (e.g., Plastic, Recycle, Pollution).', max_length=50, unique=True),
        ),
    ]
