# Generated by Django 5.2.6 on 2025-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_alter_learn_options_learn_quick_text_learn_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='topic',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
