# Generated by Django 5.2.6 on 2025-09-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('household', 'Household'), ('collector', 'Collector'), ('recycler', 'Recycler'), ('buyer', 'Buyer')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
