# Generated by Django 5.2.6 on 2025-09-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_options_user_address_user_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps link to your address (required at account setup).'),
        ),
    ]
