# Generated by Django 5.2.6 on 2025-09-20 14:54

import User.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_map_url'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', User.models.UserManager()),
            ],
        ),
    ]
