# Generated by Django 5.2.6 on 2025-09-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a clear profile photo (required at account setup for all accounts).', null=True, upload_to='user_avatars/%Y/%m/'),
        ),
    ]
