# Generated by Django 5.2.6 on 2025-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, help_text='ID/visiting card (required for Collector and Recycling Centre).', null=True, upload_to='user_ids/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps link to your address.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a clear profile photo.', null=True, upload_to='user_avatars/%Y/%m/'),
        ),
    ]
