# Generated by Django 5.2.6 on 2025-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_id_card_image_alter_user_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collector_product',
            field=models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('e_waste', 'E-waste')], help_text='Collector only: what type of material you collect.', max_length=12),
        ),
    ]
