# Generated by Django 5.2.6 on 2025-10-04 10:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_user_average_rating_user_ratings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Total points available to redeem.'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_co2_saved_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Lifetime CO₂ saved (kg).', max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='total_pickups',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime pickups/recycles.'),
        ),
    ]
