# Generated by Django 5.2.6 on 2025-09-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=True)),
                ('icon', models.CharField(max_length=20)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
