# Generated by Django 5.2.6 on 2025-10-10 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('badge', 'Badge'), ('points', 'Points'), ('order', 'Order'), ('system', 'System')], db_index=True, default='general', max_length=20)),
                ('link_url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='Notificatio_user_id_c2ea0b_idx'), models.Index(fields=['user', 'category', 'created_at'], name='Notificatio_user_id_45b7cf_idx')],
            },
        ),
    ]
