# Generated by Django 5.2.6 on 2025-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('badge', 'Badge'), ('points', 'Points'), ('order', 'Order'), ('system', 'System')], default='general', max_length=20),
        ),
    ]
